import {DISTANCE_BETWEEN_PELLETS, PIXEL_SIZE, WIDTH, HEIGHT, SIZE_OF_PELLET, GRID_SQUARE_SIZE, LEFT, UP, RIGHT, DOWN, numbers} from "./constants.js";
/*https://cdn1.vectorstock.com/i/1000x1000/10/20/pixel-english-alphabet-and-numbers-vector-18351020.jpg*/
let canvas = document.getElementById("gui");
let ctx = canvas.getContext("2d");
const LEFT_HAND_JUST = GRID_SQUARE_SIZE * (WIDTH + 2);
const LIVES_Y = GRID_SQUARE_SIZE * 20;
const LETTER_PIXEL = PIXEL_SIZE;
ctx.fillStyle = "white";
//I chose not to fully implement the alphabet since I didn't need to
//S
ctx.fillRect(LEFT_HAND_JUST + LETTER_PIXEL, LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST, 2*LETTER_PIXEL, LETTER_PIXEL, 2*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 4*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + LETTER_PIXEL, 4*LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 4*LETTER_PIXEL, 5*LETTER_PIXEL, LETTER_PIXEL, 2*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST, 6*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + LETTER_PIXEL, 7*LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
//C
ctx.fillRect(LEFT_HAND_JUST + 6*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL, 5*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 6*LETTER_PIXEL + LETTER_PIXEL, LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 6*LETTER_PIXEL + 4*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 6*LETTER_PIXEL + LETTER_PIXEL, 7*LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 6*LETTER_PIXEL + 4*LETTER_PIXEL, 6*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL);
//O
ctx.fillRect(LEFT_HAND_JUST + 12*LETTER_PIXEL + LETTER_PIXEL, LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 12*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL, 5*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 12*LETTER_PIXEL + 4*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL, 5*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 12*LETTER_PIXEL + LETTER_PIXEL, 7*LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
//R
ctx.fillRect(LEFT_HAND_JUST + 18*LETTER_PIXEL, LETTER_PIXEL, 4*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 18*LETTER_PIXEL, 5*LETTER_PIXEL, 4*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 18*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL, 7*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 18*LETTER_PIXEL + 4*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL, 3*LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 18*LETTER_PIXEL + 2*LETTER_PIXEL, 6*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 18*LETTER_PIXEL + 3*LETTER_PIXEL, 7*LETTER_PIXEL, 2*LETTER_PIXEL, LETTER_PIXEL);
//E
ctx.fillRect(LEFT_HAND_JUST + 24*LETTER_PIXEL, LETTER_PIXEL, 5*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 24*LETTER_PIXEL, 4*LETTER_PIXEL, 3*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 24*LETTER_PIXEL, 7*LETTER_PIXEL, 5*LETTER_PIXEL, LETTER_PIXEL);
ctx.fillRect(LEFT_HAND_JUST + 24*LETTER_PIXEL, LETTER_PIXEL, LETTER_PIXEL, 7*LETTER_PIXEL);

export function drawScore(score) {
 ctx.clearRect(LEFT_HAND_JUST, 9*LETTER_PIXEL, 6*LETTER_PIXEL*(score.toString()).length, 7*LETTER_PIXEL);
 for (let i = 0; i < (score.toString()).length; i++) {
   numbers[(score.toString())[i]](6*i,9, LETTER_PIXEL, LEFT_HAND_JUST, ctx);
 }
}
export function drawLives(lives, radius) {
  ctx.save();
  ctx.fillStyle = "yellow";
  ctx.clearRect(LEFT_HAND_JUST - radius*2.5, LIVES_Y - GRID_SQUARE_SIZE, LEFT_HAND_JUST + (radius*2.5)*3, LIVES_Y + (radius*2.5)*(1 + Math.floor(lives / 3)));
  for (let i = 0; i < lives - 1; i++) {
    ctx.beginPath();
    ctx.moveTo(LEFT_HAND_JUST + (radius*2.5)*(i%3), LIVES_Y + (radius*2.5)*Math.floor(i / 3));
    ctx.arc(LEFT_HAND_JUST + (radius*2.5)*(i%3), LIVES_Y + (radius*2.5)*Math.floor(i / 3), radius, Math.PI/6, 2*Math.PI - Math.PI/6);
    ctx.fill();
  }
  ctx.restore();
}